version: '3.7'

services:
    react:
        user: "${UID}:${GID}"
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/react
        networks:
            - miniature-disco
        ports:
            - "8181:8181"
        command: yarn run start

networks:
    miniature-disco:
        driver: bridge

